name: "C++ CI"

on:
  push:
    branches:
      - main
      - testing
      - feature/github_actions
  workflow_dispatch:

jobs:
  ci:
    runs-on: ubuntu-20.04
    permissions: write-all
    steps:
      # 01-homework
      - uses: actions/checkout@v3
        with:
          submodules: true
      - name: Build
        run: |
          cd ./01-homework
          sudo apt-get update && sudo apt-get install cmake libboost-test-dev -y
          mkdir -p build && cd build/
          cmake -DPATCH_VERSION=${{ github.run_number }} ../
          cmake --build .
          cmake --build . --target test
          cmake --build . --target package
          cd ..

      #02-homework
      - uses: actions/checkout@v3
        with:
          submodules: true
      - name: Build
        run: |
          cd ./02-homework
          sudo apt-get update && sudo apt-get install cmake libgtest-dev -y
          mkdir -p build && cd build/
          cmake -DPROJECT_REVISION=${{ github.run_number }} ../
          cmake --build .
          cmake --build . --target test
          cmake --build . --target package
          cd ..

      #03-homework
      - uses: actions/checkout@v3
        with:
          submodules: true
      - name: Build
        run: |
          cd ./03-homework
          sudo apt-get update && sudo apt-get install cmake libgtest-dev -y
          mkdir -p build && cd build/
          cmake -DPROJECT_REVISION=${{ github.run_number }} ../
          cmake --build .
          cmake --build . --target package

      # Release
      - name: Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        uses: softprops/action-gh-release@v1
        # if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            allocator-0.0.${{ github.run_number }}-Linux.deb
          tag_name: "homework"
          name: "Release ${{ github.run_number }}: ${{ github.event.head_commit.message }}"
          token: ${{ secrets.GITHUB_TOKEN }}
